### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by shijunil** [anutammewar/extract_triplets#1]
Hi this is a good code, but i m getting the following error message

Enter the Wikipedia Page Title
mumbai
wait for sometime! Running coreNLP.
Traceback (most recent call last):
  File "extracttriple.py", line 224, in <module>
    xmldoc = minidom.parse("input.txt.xml")# parse the xml document
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: 'input.txt.xml'

Any suggestions , why is it not able to create/locate the xml doc

**Comment by anutammewar** [comment]
Are you using the 3.5.2 version of CoreNLP?
If yes then do the following steps:
Please modify the line 223 to print the output:
print commands.getstatusoutput('java -cp "stanford-corenlp-full-2015-04-20/*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt')

And run the code again, and let me know the error message.

**Comment by shijunil** [comment]
I m using 3.5.2 version. I changed the code. The error message is as follows

Enter the Wikipedia Page Title
mumbai
wait for sometime! Running coreNLP.
(256, 'Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/pipeline/StanfordCoreNLP : Unsupported major.minor version 52.0\n\tat java.lang.ClassLoader.defineClass1(Native Method)\n\tat java.lang.ClassLoader.defineClass(ClassLoader.java:800)\n\tat java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)\n\tat java.net.URLClassLoader.defineClass(URLClassLoader.java:449)\n\tat java.net.URLClassLoader.access$100(URLClassLoader.java:71)\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:361)\n\tat java.net.URLClassLoader$1.run(URLClassLoader.java:355)\n\tat java.security.AccessController.doPrivileged(Native Method)\n\tat java.net.URLClassLoader.findClass(URLClassLoader.java:354)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)\n\tat sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)\n\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)\n\tat sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)')
Traceback (most recent call last):
  File "extracttriple.py", line 225, in <module>
    xmldoc = minidom.parse("input.txt.xml")# parse the xml document
  File "/usr/lib/python2.7/xml/dom/minidom.py", line 1918, in parse
    return expatbuilder.parse(file)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 924, in parse
    result = builder.parseFile(fp)
  File "/usr/lib/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

**Comment by shijunil** [comment]
I think i figured it out. It requires java 1.8 to be installed.

**Comment by shijunil** [comment]
I want to know how can I choose one output for each sentence(like the example u gave of Obama speech with 3 outputs) and combine them together to form a text document

**Comment by shijunil** [comment]
President Obama gave books to girls  at new jersey. President Obama gave books to girls  at India.

I commented the lines 215-220. I created a input.txt file with above sentences in the same folder. I m not getting the expected result. I m getting the following output.

wait for sometime! Running coreNLP.
DOM Element: sentence at 0x7f0540bed200, DOM Element: sentence at 0x7f0540b4c440, DOM Element: sentence at 0x7f0540b4cb00, DOM Element: sentence at 0x7f0540b533f8, DOM Element: sentence at 0x7f0540b53ab8

**Comment by anutammewar** [comment]
I am getting the attached output!
Please, once check in input.txt.xml file.
Or send it to me.

**Comment by shijunil** [comment]
pls find attached. input.txt.xml file for the the two sentences. Also
can you pls suggest me how i can get the combined output for sentences in
a input.txt file to output.txt file containing the new sentences.

**Comment by shijunil** [comment]
Did you train your code? do you have some training data?

**Comment by anutammewar** [comment]
The system is rule based, hence no training is required. It makes use of
dependency parsing and some rules over it.

**Comment by shijunil** [comment]
Hi, I have read your approach.pdf.  Sorry for asking this but can you please explain me with 1 or more examples where your code does not find the required relation and moves on to next sentence.

Thanks

**Comment by shijunil** [comment]
Hi,
Sorry, but I m new to python and still trying to understand the code. Also I wanted to how do I modify the code such that if a "noun"ie subject is not available in NP it will try to search the first "noun" in subtree of VP.

Thanks

**Comment by shijunil** [comment]
Hi i m trying to use ur approach for my project. I hope you dont mind. Thanks

**Comment by shijunil** [comment]
The code seems to be working fine. However i want to modify the code to return original sentences if the triplets are not extractable ie instead of skipping the sentence it should give the sentence as it is. I have still not been able to solve it , specifically bcoz it requires parsing the XML file. Can you please help. 
Thanks
